### ISSUE TITLE
Login Plugin doesn't block space in names (Serious)

### ISSUE THREAD

**Issue by ViktorMYT** [8bitFra/LoginReloaded#3]
Hi, I'm opening this issue because I noticed that your plugin has one very important flaw and that is that names that contain spaces are not blocked, while with all other large and small login plugins the space in the name is blocked. and that makes it a big problem for me because my server has a lot of players and I can't switch to another plugin until you fix this problem because I have too many players registered and that would cause everyone to have to re-register, and by allowing the space in the name there are some players that registered with the name "I hate nword" (this is a real case), and I cannot ban them because their name contains space, I hope that this will get fixed soon.

**Comment by 8bitFra** [comment]
I can't reproduce the problem, I tried also inserting more spaces in different places (Like "Te st st") but it seems to work. Can you give me an example where you encounter the problem? Thanks for your patience.

**Comment by 538Michael** [comment]
> I can't reproduce the problem, I tried also inserting more spaces in different places (Like "Te st st") but it seems to work. Can you give me an example where you encounter the problem? Thanks for your patience.

Basically what he said is that, people can join/register with nicknames with spaces, and with that we can't do any commands to that player, like If I've a player named "Michael Jackson", I can't use "/ban Michael Jackson", a solution to that is you kick or doesn't allow registration of nicknames with spaces.

**Comment by 8bitFra** [comment]
Thanks for the correction, I had misinterpreted the message.  I solved the problem (eb987ec).  I will release the new version today.
