### ISSUE TITLE
Can you please add the option to allow more characters on the usernames.

### ISSUE THREAD

**Issue by JimmySallofficial** [8bitFra/LoginReloaded#5]
To not have the option is a huge deal breaker for me because i am using geyser on my server and the bedrock users have * on their names and this is my favorite login plugin. :/ Thanks for this amazing plugin!

**Comment by 8bitFra** [comment]
I don't think a minecraft server will allow you to use the character * regardless of the plugin. If you want I can put an option to ignore the name check and allow illegal characters, however this is not something I would advise you to do. The solution could be to use _ which is a character recognized by the game.

**Comment by JimmySallofficial** [comment]
Authme has this option (but i will try that as well maybe in the future) and yes i will like to have this option if it isn't hard to put. 
allowedNicknameCharacters: '[a-zA-Z0-9_]*'
in your AuthMe config should be changed to
allowedNicknameCharacters: '\*?[a-zA-Z0-9_]*'
Have a nice day and thanks for the support!

**Comment by 8bitFra** [comment]
Thanks for the tip, actually doing this check is very easy via regex, the operation should be similar to how AuthMe implemented it, however I repeat that in minecraft you cannot have * in the name, I recommend you change the symbol. I will release the new version tonight. d07507f
